<script setup lang="ts">
import { Link, usePage } from '@inertiajs/vue3';
import PlatformLayout from '@/Layouts/PlatformLayout.vue';

interface Category { used: number; limit: number | null; remaining: number | null; percentage: number | null }
interface Subscription { id: string; tenant: { id: string; name: string; slug: string }; plan: { id: string; name: string; slug: string; price_monthly: string; price_yearly: string }; status: string; started_at: string | null; current_period_start: string | null; current_period_end: string | null; cancel_at_period_end: boolean; provider: string; provider_subscription_id: string | null }
const page = usePage();
const props = defineProps<{ subscription: Subscription; usage: { period_start: string; period_end: string; categories: Record<string, Category> } | null; audit: { id: string; action: string; created_at: string; actor_name: string | null }[] }>();
const date = (value: string | null): string => value ? new Intl.DateTimeFormat('en', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Not available';
const limit = (value: number | null): string => value === null ? 'Unlimited' : value.toLocaleString();
</script>

<template>
    <PlatformLayout :user="page.props.auth.user">
        <Link href="/platform/subscriptions" class="text-sm font-semibold text-[#0b8f5a]">← Back to Subscriptions</Link>
        <div class="mt-5 flex flex-wrap items-start justify-between gap-4"><div><p class="app-eyebrow">Subscription detail</p><h1 class="mt-2 text-3xl font-semibold">{{ props.subscription.tenant.name }}</h1><p class="mt-2 text-sm text-[#71877b]">{{ props.subscription.tenant.slug }} · {{ props.subscription.plan.name }}</p></div><Link :href="`/platform/customers/${props.subscription.tenant.id}/subscription/edit`" class="app-button app-button--secondary">Change plan</Link></div>
        <section class="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div class="app-card p-5"><p class="app-eyebrow">Status</p><p class="mt-2 font-semibold capitalize">{{ props.subscription.status.replaceAll('_', ' ') }}</p></div><div class="app-card p-5"><p class="app-eyebrow">Provider</p><p class="mt-2 font-semibold capitalize">{{ props.subscription.provider }}</p><p v-if="props.subscription.provider_subscription_id" class="mt-1 text-xs text-[#71877b]">{{ props.subscription.provider_subscription_id }}</p></div><div class="app-card p-5"><p class="app-eyebrow">Started</p><p class="mt-2 font-semibold">{{ date(props.subscription.started_at) }}</p></div><div class="app-card p-5"><p class="app-eyebrow">Current period</p><p class="mt-2 text-sm font-semibold">{{ date(props.subscription.current_period_start) }} to {{ date(props.subscription.current_period_end) }}</p></div></section>
        <section class="app-card mt-6 p-6"><div class="flex flex-wrap items-baseline justify-between gap-3"><div><h2 class="text-lg font-semibold">Usage and limits</h2><p v-if="props.usage" class="mt-1 text-sm text-[#71877b]">{{ date(props.usage.period_start) }} to {{ date(props.usage.period_end) }}</p></div></div><div v-if="props.usage" class="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><div v-for="(item, category) in props.usage.categories" :key="category" class="rounded-xl bg-[#f5f8f4] p-4"><div class="flex justify-between gap-3"><p class="text-sm font-medium capitalize">{{ String(category).replaceAll('_', ' ') }}</p><p class="text-xs text-[#71877b]">{{ item.percentage === null ? '—' : `${item.percentage}%` }}</p></div><p class="mt-2 text-xl font-semibold">{{ item.used.toLocaleString() }} <span class="text-sm font-normal text-[#71877b]">/ {{ limit(item.limit) }}</span></p></div></div><p v-else class="mt-4 text-sm text-[#60766a]">No active subscription usage is available.</p></section>
        <section class="app-card mt-6 p-6"><h2 class="text-lg font-semibold">Audit</h2><p class="mt-1 text-sm text-[#71877b]">Safe metadata only. Provider secrets and audit payloads are never shown.</p><div v-if="props.audit.length" class="mt-4 divide-y divide-[#edf2ec]"><div v-for="entry in props.audit" :key="entry.id" class="flex flex-wrap justify-between gap-2 py-3"><div><p class="font-medium">{{ entry.action }}</p><p class="text-xs text-[#71877b]">{{ entry.actor_name ?? 'System' }}</p></div><time class="text-xs text-[#71877b]">{{ date(entry.created_at) }}</time></div></div><p v-else class="mt-4 text-sm text-[#60766a]">No audit activity recorded.</p></section>
    </PlatformLayout>
</template>
